### ISSUE TITLE
Question about evolution of PyNIDM and NIDM 

### ISSUE THREAD

**Issue by stimon** [incf-nidash/PyNIDM#38]
Hi!

How different is the development of the actual NIDM ontology (especially NIDM-experiment) from this library?

I get the feel that this library evolves faster than the ontology, at least from what the repo contains. 
It looks like there are a lot of terms referenced in the constants files that are missing or still not coded in the actual NIDM owl file. 

Maybe I am missing something?

Thanks!
Santi

**Comment by khelm** [comment]
Hi @stimon  - no you're not missing something.  The ontology and the library are both evolving rapidly at this point and there are a lot of fundamental changes happening on a weekly basis at the moment as they both are built out.  I would say that things should be a bit more stable in a month or so.  The ontology itself and the import of terms from other ontologies are being simplified at the moment, but in parallel with the development of the library so that is what you are seeing.  I will keep you posted on the ontology status in the near future.

**Comment by stimon** [comment]
Thanks a lot for the clarification @khelm, that makes sense 🙂
